name: Build PHP
on:
  push:
  pull_request:
  repository_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    name: Build PHP ${{ matrix.php-version }} on ${{ matrix.operating-system }}
    if: "!contains(github.event.head_commit.message, 'skip-build')"
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-20.04, ubuntu-18.04, ubuntu-16.04]
        php-version: ['8.0', '8.1']
        include:
          - operating-system: ubuntu-20.04
            libs: "libgccjit-10-dev"
          - operating-system: ubuntu-18.04
            libs: "libgccjit-8-dev"
          - operating-system: ubuntu-16.04
            libs: "libgccjit-6-dev"
    steps:
      - name: Install required packages
        run: |
          existing_version=$(curl -sL https://github.com/shivammathur/php-builder/releases/latest/download/php${{ matrix.php-version }}.log)
          new_version=$(curl -sL https://api.github.com/repos/php/php-src/git/refs/tags | grep -Po "php-${{ matrix.php-version }}.[0-9]+" | tail -n 1)
          if [[ "${{ github.event.head_commit.message }}" = *build-all* ]] || [ "$new_version" != "$existing_version" ]; then
            debconf_fix="DEBIAN_FRONTEND=noninteractive"
            if ! apt-cache policy | grep -q ondrej/php; then
              LC_ALL=C.UTF-8 sudo apt-add-repository ppa:ondrej/php -y || true
            fi
            sudo "$debconf_fix" apt-get update || true
            sudo "$debconf_fix" apt-fast -y install gcc-7 g++-7 expect locales language-pack-de re2c mysql-server postgresql pkg-config libaspell-dev libbz2-dev libbison-dev libedit-dev libcurl4-gnutls-dev libenchant-dev libffi-dev libfreetype6-dev ${{ matrix.libs }} libargon2-dev libmagickwand-dev libgmp-dev libicu-dev libjpeg-dev libwebp-dev libc-client2007e-dev libkrb5-dev libldap-dev libonig-dev libmcrypt-dev libpng-dev libpq5 libpq-dev libreadline-dev libpspell-dev libsasl2-dev libsnmp-dev libssl-dev libsqlite3-dev libsodium-dev libtidy-dev libwebp-dev libxml2-dev libxpm-dev libxslt1-dev libzip-dev
            sudo ln -sf /usr/lib/libc-client.so.2007e.0 /usr/lib/x86_64-linux-gnu/libc-client.a
            sudo mkdir -p /usr/c-client/
            sudo ln -sf /usr/lib/libc-client.so.2007e.0 /usr/c-client/libc-client.a
            sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 7
            sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 7
          fi
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and ship
        run: chmod a+x .github/scripts/build.sh && .github/scripts/build.sh
        env:
          GITHUB_USER: ${{ github.repository_owner }}
          GITHUB_MESSAGE: ${{ github.event.head_commit.message }}
          GITHUB_NAME: 'Shivam Mathur'
          GITHUB_EMAIL: ${{ secrets.email }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          BINTRAY_KEY: ${{ secrets.bintray_key }}
          BINTRAY_USER: ${{ github.repository_owner }}
          BINTRAY_REPO: php
          PHP_VERSION: ${{ matrix.php-version }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: php_${{ matrix.php-version }}+${{ matrix.operating-system }}
          path: |
            /usr/local/php/*.xz
            /usr/local/php/*.zst
      - name: Test versions
        run: |
          php -v | head -n 1
          php-cgi -v | head -n 1
          phpdbg -V | head -n 1
          pecl -V
          php-config --version
          phpize -v
          php -m
      - name: Benchmark
        run: |
          printf "Benchmark with PHP7.4\n"
          sudo phpdismod -v 7.4 xdebug
          curl https://raw.githubusercontent.com/php/php-src/master/Zend/bench.php | php7.4
          printf "Benchmark with PHP${{ matrix.php-version }}\n"
          curl https://raw.githubusercontent.com/php/php-src/master/Zend/bench.php | php
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - run: mkdir builds
      - uses: actions/download-artifact@v2
        with:
          path: builds
      - name: Release
        run: chmod a+x .github/scripts/release.sh && .github/scripts/release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
